---
title: "ex5"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## What is complex contagion and how it’s different from simple contagion?

Simple contagion refers to the spreading behavior by sigle influencer in the network. In this case, we only need one influencer to speard certain behaviors or ideasin the social network. While, would need multiple influencers in the social network inorder to spread the idea.

Apart from the definition, simple contagion and complex contagion are also different in the way they spread the ideas or behavior. In the simple contagion case, if a node has more degree, it will spread more ideas or behaviors to others. However, in the complex contagion case, even if one node has a large degree, it cannot easily spread an idea to a node with also high degree. Because it will require a group's power to spread the ideas or behaviors.

## What does complex contagion mean for diffusion of behaviors in organization?

In a organization, complex contagion means our behavior is affected by the organizaion's network, especially those person you are connected to. For example, if a company is using hybird working method and most of your peer in the office choose to work onsite, you will probabily work onsite too. This is a kind of "peer presure". However, if your department is not well connect to other department, even if 70% of the company work remotely, you and your peer would still work onsite. Because if two cluster of people are not well connected, ideas are hard to spread from one group to another. In this case, if a orgamization wants to spread a idea, it should carefully choose the people that are in charge of this diffusion behavior.

## How can we use the threshold models to better manage

In order to use the threshold models to spread the ideas within organization, the manager should first evaluate the threshold values for different tasks. Once the value is decided, managers should find someone in the organization who already pocess this idea or someone who is willing to adopt this idea at the starting point. After finding the spreaders, managers should instruct those people to target on the person in their network that has the lowest connection number, because those people are more likely to adopt new ideas. Then they will become the spreaders. As the process begin, the spreading process will eventually reach its optimal status.


